# Generated by Django 3.0.4 on 2021-04-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210426_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='des',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
    ]
